// Generates src/admin/logos.ts (data only) from the simple-icons package plus
// a small hand-maintained fallback for brands simple-icons has removed
// (trademark policy: Slack, OpenAI, AWS, LinkedIn, ...). Every integration id
// gets a BrandLogo: a real single-path SVG when we have one, otherwise the
// render helper draws a monogram tile in the brand colour. The render helper
// lives in src/admin/logo-render.ts. Run: node scripts/gen-logos.mjs
import * as si from "simple-icons";
import { writeFileSync } from "node:fs";

// integration id -> simple-icons export slug (camel of the icon slug).
const SLUGS = {
  github: "github", google: "google", gemini: "googlegemini", gcp: "googlecloud",
  anthropic: "anthropic", openrouter: "openrouter", jira: "jira", notion: "notion",
  linear: "linear", stripe: "stripe", "brave-search": "brave", "telegram-bot": "telegram",
  discord: "discord", huggingface: "huggingface", gitlab: "gitlab", confluence: "confluence",
  dropbox: "dropbox", cloudflare: "cloudflare", vercel: "vercel", supabase: "supabase",
  resend: "resend", todoist: "todoist", trello: "trello", "mongodb-atlas": "mongodb",
  docker: "docker", "jfrog-artifactory": "jfrog", "github-app": "github",
  elevenlabs: "elevenlabs", make: "make", flyio: "flydotio", hetzner: "hetzner",
};

// Brands simple-icons no longer ships: monogram fallback (title + brand hex).
const FALLBACK = {
  slack: { title: "Slack", hex: "611F69" },
  openai: { title: "OpenAI", hex: "10A37F" },
  aws: { title: "AWS", hex: "FF9900" },
  sendgrid: { title: "SendGrid", hex: "1A82E2" },
  monday: { title: "monday", hex: "FF3D57" },
  linkedin: { title: "LinkedIn", hex: "0A66C2" },
  tavily: { title: "Tavily", hex: "3B82F6" },
};

const exportFor = (slug) => "si" + slug.charAt(0).toUpperCase() + slug.slice(1);

const out = {};
for (const [id, slug] of Object.entries(SLUGS)) {
  const icon = si[exportFor(slug)];
  if (!icon) throw new Error(`simple-icons missing ${slug} for ${id}`);
  out[id] = { title: icon.title, hex: icon.hex, path: icon.path };
}
for (const [id, meta] of Object.entries(FALLBACK)) {
  out[id] = { title: meta.title, hex: meta.hex }; // no path -> monogram tile
}

const entries = Object.entries(out)
  .map(([id, v]) => {
    const path = v.path ? `, path: ${JSON.stringify(v.path)}` : "";
    return `  ${JSON.stringify(id)}: { title: ${JSON.stringify(v.title)}, hex: ${JSON.stringify(v.hex)}${path} },`;
  })
  .join("\n");

const header = [
  "/**",
  " * Brand logos for the self-service connect pages. GENERATED by",
  " * scripts/gen-logos.mjs from simple-icons (single-path 24x24 marks) plus a",
  " * hand-maintained monogram fallback for brands simple-icons has removed",
  " * (trademark policy). Do not edit by hand: re-run the generator. The render",
  " * helper lives in logo-render.ts.",
  " *",
  " * A BrandLogo with a path renders as the real vendor mark; without one it",
  " * renders as a monogram tile in the brand colour. Every integration shown in",
  " * a connect wizard has an entry, so the page always pairs a vendor mark with",
  " * the OneGate keyhole.",
  " */",
  "",
  "export interface BrandLogo {",
  "  title: string;",
  "  /** Brand hex WITHOUT the leading '#'. */",
  "  hex: string;",
  "  /** simple-icons single-path data (24x24 viewBox). Absent = monogram tile. */",
  "  path?: string;",
  "}",
  "",
  "export const INTEGRATION_LOGOS: Record<string, BrandLogo> = {",
].join("\n");

const file = `${header}\n${entries}\n};\n`;

writeFileSync(new URL("../src/admin/logos.ts", import.meta.url), file);
console.log(`wrote src/admin/logos.ts with ${Object.keys(out).length} logos`);
